# Generated by Django 2.2.3 on 2019-08-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190810_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
