# Generated by Django 2.2.3 on 2019-08-12 16:46

from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20190810_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='audio_tune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_tune', to='music.Tune'),
        ),
        migrations.AddField(
            model_name='volume',
            name='composer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='composer', to='music.Player'),
        ),
        migrations.AddField(
            model_name='volume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=music.models.volume_img_path),
        ),
        migrations.AddField(
            model_name='volume',
            name='video_tune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_tune', to='music.Tune'),
        ),
    ]
