# Generated by Django 2.2.3 on 2019-08-12 17:02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20190812_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='tune',
            name='band',
            field=ckeditor.fields.RichTextField(default='list of musicians'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='audio_tune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_tune', to='music.Tune'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='composer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='composer', to='music.Player'),
        ),
        migrations.AlterField(
            model_name='volume',
            name='video_tune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_tune', to='music.Tune'),
        ),
    ]
