# Generated by Django 2.2.4 on 2019-09-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20190812_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'Draft'), ('p', 'Published')], default='d', max_length=1),
        ),
    ]
