# Generated by Django 2.2.4 on 2019-09-11 11:19

from django.db import migrations, models
import music.util


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20190911_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='amazon',
            field=models.CharField(blank=True, help_text='Link to volume on Amazon', max_length=500),
        ),
        migrations.AddField(
            model_name='volume',
            name='apple_music',
            field=models.CharField(blank=True, help_text='Link to volume on Apple Music', max_length=500),
        ),
        migrations.AddField(
            model_name='volume',
            name='bandcamp',
            field=models.CharField(blank=True, help_text='Link to volume on BandCamp', max_length=500),
        ),
        migrations.AddField(
            model_name='volume',
            name='spotify',
            field=models.CharField(blank=True, help_text='Link to volume on Spotify', max_length=500),
        ),
        migrations.AlterField(
            model_name='tune',
            name='image',
            field=models.ImageField(blank=True, help_text='Only need an image for the video tune', null=True, upload_to=music.util.tune_image_directory_path),
        ),
        migrations.AlterField(
            model_name='volume',
            name='pre_order',
            field=models.CharField(blank=True, help_text='For this to appear on the homepage: the volume must be in draft and both release date and preorder must be filled in', max_length=500),
        ),
        migrations.AlterField(
            model_name='volume',
            name='release_date',
            field=models.CharField(blank=True, help_text='For this to appear on the homepage: the volume must be in draft and both release date and preorder must be filled in', max_length=200),
        ),
    ]
