# Generated by Django 2.2.4 on 2019-09-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20190911_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='tune',
            name='bandcamp_embed',
            field=models.CharField(blank=True, help_text='Simply paste the html from the bandcamp embed player (on the bandcamp website) for the audio-only tune', max_length=500),
        ),
    ]
