# Generated by Django 2.2.4 on 2019-09-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_tune_bandcamp_embed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tune',
            name='bandcamp_embed',
            field=models.CharField(blank=True, help_text='Simply paste the html from the bandcamp embed player (on the bandcamp website) for the audio-only tune. Choose the thinnest embedding option.', max_length=500),
        ),
        migrations.AlterField(
            model_name='tune',
            name='video_embed',
            field=models.CharField(blank=True, default='', help_text='Paste the URL to the youtube video', max_length=300, verbose_name='Youtube URL'),
        ),
    ]
