# Generated by Django 2.2.4 on 2019-09-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoVerse', '0004_player_gigged_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gigged_with',
            field=models.ManyToManyField(blank=True, related_name='_player_gigged_with_+', to='DjangoVerse.Player'),
        ),
    ]
