# Generated by Django 2.2.4 on 2019-09-24 16:23

import DjangoVerse.models
import DjangoVerse.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoVerse', '0006_player_video_embed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=DjangoVerse.storage.OverwriteStorage(), upload_to=DjangoVerse.models.player_img_path),
        ),
    ]
