# Generated by Django 2.2.4 on 2019-09-24 16:44

import DjangoVerse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoVerse', '0008_auto_20190924_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=DjangoVerse.models.player_img_path),
        ),
    ]
