# Generated by Django 2.2.4 on 2019-09-25 21:40

import DjangoVerse.models
import DjangoVerse.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoVerse', '0009_auto_20190924_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gigged_with',
            field=models.ManyToManyField(blank=True, help_text="\n<p>Choose people this player has gigged with (ie: done a concert with). Note that jams don't count!</p>\n<hr>\n<p><span style='font-weight:bold'>On desktop:</span> double click on a player to select them</p>\n<p style='font-weight:bold'>On mobile:</p>\n<ol>\n<li>Click on the gray box in the 'available gigged with' group, choose some players, and click OK.</li>\n<li>Click on the downward arrow to move the players to the 'chosen gigged with' group</li>\n</ol>\n", related_name='_player_gigged_with_+', to='DjangoVerse.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, help_text='If the width is not 1.5 times the height, then the image will be cropped to make it so.', null=True, storage=DjangoVerse.storage.OverwriteStorage(), upload_to=DjangoVerse.models.player_img_path),
        ),
        migrations.AlterField(
            model_name='player',
            name='instrument',
            field=models.ManyToManyField(help_text="\n<p>This field is required!</p>\n<hr>\n<p><span style='font-weight:bold'>On desktop:</span> double click on an instrument to select it</p>\n<p style='font-weight:bold'>On mobile:</p>\n<ol>\n<li>Click on the gray box in the 'available instrument' group, choose an instrument, and click OK.</li>\n<li>Click on the downward arrow to move the instrument to the 'chosen instrument' group</li>\n</ol>\n", to='DjangoVerse.Instrument'),
        ),
        migrations.AlterField(
            model_name='player',
            name='isactive',
            field=models.BooleanField(default=True, help_text="Whether or not they're active on the Gypsy Jazz scene today"),
        ),
        migrations.AlterField(
            model_name='player',
            name='video_embed',
            field=models.CharField(blank=True, default='', help_text="Paste the URL to a youtube video of this player's music", max_length=300, verbose_name='Youtube URL'),
        ),
    ]
