# Generated by Django 2.2.4 on 2019-09-25 23:16

import DjangoVerse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoVerse', '0010_auto_20190925_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, help_text='If the width is not 1.5 times the height, then the image will be cropped to make it so.', null=True, upload_to=DjangoVerse.models.player_img_path),
        ),
    ]
