# Generated by Django 2.2.4 on 2019-09-25 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoVerse', '0011_auto_20190925_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='band',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='festival',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='thumbnail',
        ),
    ]
