# Generated by Django 2.2.4 on 2019-10-11 18:57

import DjangoVerse.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoVerse', '0012_auto_20190925_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='gigged_with',
            field=models.ManyToManyField(blank=True, related_name='_player_gigged_with_+', to='DjangoVerse.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, help_text='<p>The image should be <b>landscape</b> rather than portrait. (ie: horizontal rather than vertical).</p><p>If the width is not 1.5 times the height, then the image will be cropped to make it so.</p>', null=True, upload_to=DjangoVerse.models.player_img_path),
        ),
        migrations.AlterField(
            model_name='player',
            name='instrument',
            field=models.ManyToManyField(to='DjangoVerse.Instrument'),
        ),
        migrations.AlterField(
            model_name='player',
            name='video_embed',
            field=models.CharField(blank=True, default='', help_text="<p>Paste the URL of a <b>youtube video</b> of this player's music.</p> <p><b>Note: don't paste the link to a youtube account :)</b></p>", max_length=300, verbose_name='Youtube URL'),
        ),
    ]
